package com.raphael.asyncorderprocessing.enums;

public enum CategoryEnum {

    ALIMENTOS_E_BEBIDAS,
    AUTOMOTIVO,
    BEBE_E_CIA,
    BELEZA_E_PERFUMARIA,
    BRINQUEDOS_E_JOGOS,
    CAMA_MESA_E_BANHO,
    CASA_E_DECORACAO,
    CONSTRUCAO_E_FERRAMENTAS,
    ELETRONICOS,
    ELETRODOMESTICOS,
    ELETROPORTATEIS,
    ESPORTE_E_LAZER,
    GAMES,
    INFORMATICA,
    INSTRUMENTOS_MUSICAIS,
    LIVROS,
    MODA_E_ACESSORIOS,
    PET_SHOP,
    SAUDE_E_BEM_ESTAR,
    PAPELARIA_E_ESCRITORIO



}
